[package]
name = "zed_postgres_model_context"
version = "0.0.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/postgres_model_context.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
zed_extension_api = "0.2.0"
